rockclimbing/rockclimbing/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('routeguide.urls')),
]

rockclimbing/routeguide/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'routeguide'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^indoor/$', views.indoor, name='indoor'),
    url(r'indoor/(?P<gym_id>[0-9]+)/$', views.indoor_gym, name='indoor_gym'),
]

rockclimbing/routeguide/models.py
from django.db import models

class Gym(models.Model):
    name = models.CharField(max_length=250)
    province = models.CharField(max_length=100)
    city = models.CharField(max_length=250)
    address = models.CharField(max_length=500)
    gym_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.name + ' - ' + self.city + ', ' + self.province

class Route(models.Model):
    gym = models.ForeignKey(Gym, on_delete=models.CASCADE)
    difficulty = models.CharField(max_length=100)
    climb_type = models.CharField(max_length=100)
    climb_picture = models.CharField(max_length=500)
    is_up = models.BooleanField(default=True)

    def __str__(self):
        return self.climb_type + ' - ' + self.difficulty

rockclimbing/routeguide/views.py
from django.shortcuts import render
from .models import Gym, Route
from django.http import Http404

def index(request):
    return render(request, 'routeguide/index.html')

def indoor(request):
    all_gyms = Gym.objects.all()
    return render(request, 'routeguide/indoor.html', {'all_gyms': all_gyms})

def indoor_gym(request, gym_id):
    try:
        gym = Gym.objects.get(pk=gym_id)
    except Gym.DoesNotExist:
        raise Http404('Gym does not exist')

    return render(request, 'routeguide/gym.html', {'gym': gym})

rockclimbing/routeguide/templates/routeguide/base.html
<!-- Navbar and imports -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The Beta</title>
    {% load staticfiles %}
    <link href="https://fonts.googleapis.com/css?family=Plaster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gruppo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cutive+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'routeguide/style.css' %}" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-field">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="topNavBar">

                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                </button>
                <a class="navbar-brand" href="/index/">The Beta</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">

                    <li class="">
                        <a href="/index/indoor/">
                            <span aria-hidden="true"></span> Indoor
                        </a>
                    </li>

                    <li class="">
                        <a href="#">
                            <span aria-hidden="true"></span> Outdoor
                        </a>
                    </li>

                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="#">
                            <span class='glyphicon glyphicon-question-sign' aria-hidden="true"></span> About
                        </a>
                    </li>

                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

rockclimbing/routeguide/templates/routeguide/gym.html
{% extends 'routeguide/base.html' %}

{% block body %}
    <img id="gym_id_logo" src="{{ gym.gym_logo }}">
    <h1 style="text-align:center; padding-top:2em">List of Routes at {{ gym.name }}</h1>

    <!-- Showing list of active routes -->
    <div class="container">
            <div class="row">
                <ul>
                    {% for route in gym.route_set.all %}
                        {% if route.is_up == True %}
                            <div class="col-8 col-md-4 text-center"  style="margin:0 auto">
                                <a href="#"><img style="padding-top:30px" class = 'route_pic' src="{{ route.climb_picture }}"></a>
                                <li class="route_details">{{ route }}</li>
                            </div>
                        {% endif %}
                    {% endfor %}
                </ul>
        </div>
    </div>

{% endblock %}

rockclimbing/routeguide/templates/routeguide/index.html
{% extends 'routeguide/base.html' %}

{% block body %}

    <!-- Changing The Background -->
    <style>
        body {
            background: gray url('../../static/routeguide/images/mountain.jpg');
        }
    </style>

    <!-- Title and Description -->
    <h1 id="center-heading">Welcome to <span><h1 id="center-logo">The Beta</h1></span></h1>
    <p id="description">The Beta is a simple web application where users can upload <br>
        their method of completing various rock climbing routes.<br> Begin by selecting
        indoor or outdoor locations.</p>
    <div id="iobtn_wrapper">
        <a href="/index/indoor/"><button class="io_btn" type="button">Indoor</button></a>
        <a href="#"><button class="io_btn" type="button">Outdoor</button></a>
    </div>

{% endblock %}

rockclimbing/routeguide/templates/routeguide/indoor.html
{% extends 'routeguide/base.html' %}

{% block body %}

    <!-- Changing The Background -->
    <style>
        body {
            background: gray url('../../static/routeguide/images/boulderwall.jpg');
        }
    </style>

    <!-- Generate list of gyms -->
    {% if all_gyms %}
        <div class="container" id="gymlist_bg">
            <h1 id="index_header">List of Indoor Climbing Gyms</h1>
            <div class="row">
                <ul class='gymlist'>
                    {%  for gym in all_gyms %}
                        <div class="col-6 col-md-3">
                            <a href="/index/indoor/{{ gym.id }}/">
                                <img style="border-radius:150px" src="{{ gym.gym_logo }}" class="gym_logo">
                            </a>
                            <li class='gym_name' style="padding:10px 10px 15px 10px list-style-type: none">
                                <span style="font-size:1.35em; color:deepskyblue">{{ gym.name }}</span><br>
                                    {{ gym.city }} - {{ gym.province }}
                            </li>
                        </div>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% else %}
        <p>There are no gyms.</p>
    {% endif %}

{% endblock %}